import time
import os
from getch import getche, getch

# screen resolution 20x53 char
def startup():
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("          __  ___             __ _        __         ")
    print("         /  |/  /___ _ _  __ / /(_)___   / /__       ")
    print("        / /|_/ // _ `/| |/ // // // _ \ /  '_/       ")
    print("       /_/  /_/ \_,_/ |___//_//_//_//_//_/\_\        ")
    print("        ______                 __                    ")
    print("       /_  __/____ ___ _ ____ / /__ ___  ____        ")
    print("        / /  / __// _ `// __//  '_// -_)/ __/        ")
    print("       /_/  /_/   \_,_/ \__//_/\_\ \__//_/           ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    
    time.sleep(2)

    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("          __  ___             __ _        __         ")
    print("         /  |/  /___ _ _  __ / /(_)___   / /__       ")
    print("        / /|_/ // _ `/| |/ // // // _ \ /  '_/       ")
    print("       /_/  /_/ \_,_/ |___//_//_//_//_//_/\_\        ")
    print("        ______                 __                    ")
    print("       /_  __/____ ___ _ ____ / /__ ___  ____        ")
    print("        / /  / __// _ `// __//  '_// -_)/ __/        ")
    print("       /_/  /_/   \_,_/ \__//_/\_\ \__//_/           ")
    print("                                                     ")
    print("                                                     ")
    print('{:^53}'.format('Press any button to continue...'))
    print("                                                     ")
    print("                                                     ")
    print("   A              B               C              D   ")
    getch()

def print_center(text):
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print('{:^53}'.format(text))
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("   A              B               C              D   ")

def print_center_yesno(text):
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print('{:^53}'.format(text))
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("                                                     ")
    print("  Yes            No                                  ")

def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')